[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

CoreNumber=0
CoreCaption="CPU (All Cores)"

FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
BarColor=#ColorUsage#,#BarColorTransparency#
HistoLineColor=#ColorUsage#,#LineColorTransparency#
HistoFillColor=#ColorUsage#,#HistoColorTransparency#

SkinIcon=#IconCPU#
