;==============================================================================
; Grayhound Variables
;
; @category: Rainmeter
; @package: Grayhound
; @version: 5.6.1
; @date: 2024-06-29
; @author: George Lewe <george@lewe.com>
; @copyright: 2012-2024 by George Lewe
; @link: http://www.lewe.com
; @license: https://creativecommons.org/licenses/by-nc-sa/3.0/
; @documentation: https://lewe.gitbook.io/rainmeter-skin-grayhound
;

[Variables]
;
; Skin settings
;
;IconXPos=#IconXPosLeft#
;MeterXPos=#MeterXPosLeft#
IconXPos=#IconXPosRight#
MeterXPos=#MeterXPosRight#

FontColor=#FontColorGlobal#,255
FontFace=#FontFaceGlobal#
BarColor=#ColorFan#,#BarColorTransparency#
HistoLineColor=#ColorFan#,#LineColorTransparency#
HistoFillColor=#ColorFan#,#HistoColorTransparency#
SkinIcon=#IconFan#


;
; Fan scale maximum
;
MaxFan=8000
MaxFan1=#MaxFan#
MaxFan2=#MaxFan#
MaxFan3=#MaxFan#
MaxFan4=#MaxFan#
MaxFan5=#MaxFan#
MaxFan6=#MaxFan#

;
; RPM Thresholds
; These values define when the color turns
;
MedFan=4000
HiFan=6500

MedFan1=#MedFan#
HiFan1=#HiFan#
MedFan2=#MedFan#
HiFan2=#HiFan#
MedFan3=#MedFan#
HiFan3=#HiFan#
MedFan4=#MedFan#
HiFan4=#HiFan#
MedFan5=#MedFan#
HiFan5=#HiFan#
MedFan6=#MedFan#
HiFan6=#HiFan#

;
; Captions
;
CaptionFan="FAN SPEED"
CaptionFan1="CPU"
CaptionFan2="Front Panel"
CaptionFan3="Bottom Panel"
CaptionFan4="Rear Fan"
CaptionFan5="---"
CaptionFan6="---"
