;==============================================================================
; Grayhound Variables
;
; @category: Rainmeter
; @package: Grayhound
; @version: 5.6.0
; @date: 2024-06-22
; @author: George Lewe <george@lewe.com>
; @copyright: 2012-2024 by George Lewe
; @link: http://www.lewe.com
; @license: https://creativecommons.org/licenses/by-nc-sa/3.0/
; @documentation: https://lewe.gitbook.io/rainmeter-skin-grayhound
;

[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;lIconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
SkinIcon=#IconAIO#

;
; Temperature unit
;
TempUnit=C

;
; Scale maximums
;
MaxFan1=2100
MaxFan2=2100
MaxCPUPump=6000
MaxCPUCoolant=120

;
; Thresholds
; These values define when the color turns
;
MedFan1=700
HiFan1=1400

MedFan2=700
HiFan2=1400

MedCPUPump=2000
HiCPUPump=4000

MedCPUCoolant=40
HiCPUCoolant=70

;
; Captions
;
Caption="Corsair H115i"
CaptionFan1="Fan 1"
CaptionFan2="Fan 2"
CaptionCPUPump="CPU Pump"
CaptionCPUCoolant="CPU Coolant"
