;==============================================================================
; Grayhound Variables
;
; @category: Rainmeter
; @package: Grayhound
; @version: 5.6.0
; @date: 2024-06-22
; @author: George Lewe <george@lewe.com>
; @copyright: 2012-2024 by George Lewe
; @link: http://www.lewe.com
; @license: https://creativecommons.org/licenses/by-nc-sa/3.0/
; @documentation: https://lewe.gitbook.io/rainmeter-skin-grayhound
;

[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

Core0Number=0
Core1Number=1
Core2Number=2
Core3Number=3
Core4Number=4
Core5Number=5
Core6Number=6
Core7Number=7
Core8Number=8
Core9Number=9
Core10Number=10
Core11Number=11
Core12Number=12
Core13Number=13
Core14Number=14
Core15Number=15
Core16Number=16
Caption="CPU"

FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
BarColor=#ColorUsage#,#BarColorTransparency#
HistoLineColor=#ColorUsage#,#LineColorTransparency#
HistoFillColor=#ColorUsage#,#HistoColorTransparency#
CoreBarWidth=#CoreBarWidth16Cores#
CoreBarXDist=#CoreBarXDist16Cores#
CoreBarYRel=#CoreBarYRel16Cores#
SkinIcon=#IconCPU#
