[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

Drive1Letter="C:"
Drive2Letter="D:"
Drive3Letter="E:"

FontColor=#FontColorGlobal#,255
FontFace=#FontFaceGlobal#
BarColor=#ColorDisk#,#BarColorTransparency#
HistoLineColor=#ColorDisk#,#LineColorTransparency#
HistoFillColor=#ColorDisk#,#HistoColorTransparency#
SkinIcon=#IconDisk#
