[Variables]
;
; Skin settings
;
;IconXPos=#IconXPosLeft#
;MeterXPos=#MeterXPosLeft#
;TrackXPos=#TrackXPosLeft#
IconXPos=#IconXPosRight#
MeterXPos=#MeterXPosRight#
TrackXPos=#TrackXPosRight#

ProgressBarColor=#ColorTemp#,120
ProgressBarColorBgFrom=#BarColorBgFrom#
ProgressBarColorBgTo=#BarColorBgTo#
SpectrumBarColor=#Blue#,100
SpectrumBarHeight=#SBarHeight#
SpectrumBarWidth=#SBarWidth#
SpectrumBarMargin=#SBarMargin#
FontColor=#FontColorGlobal#, 255
FontFace=#FontFaceGlobal#
SkinIcon=#IconMusic#

Caption="NOW PLAYING"
MusicPlayer=AIMP
