;==============================================================================
; Grayhound Variables
;
; @category: Rainmeter
; @package: Grayhound
; @version: 5.6.0
; @date: 2024-06-22
; @author: George Lewe <george@lewe.com>
; @copyright: 2012-2024 by George Lewe
; @link: http://www.lewe.com
; @license: https://creativecommons.org/licenses/by-nc-sa/3.0/
; @documentation: https://lewe.gitbook.io/rainmeter-skin-grayhound
;

[Variables]
;
; Skin settings
;
;IconXPos=#IconXPosLeft#
;MeterXPos=#MeterXPosLeft#
;TrackXPos=#TrackXPosLeft#
IconXPos=#IconXPosRight#
MeterXPos=#MeterXPosRight#
TrackXPos=#TrackXPosRight#

ProgressBarColor=#ColorTemp#,120
ProgressBarColorBgFrom=#BarColorBgFrom#
ProgressBarColorBgTo=#BarColorBgTo#
SpectrumBarColor=#Blue#,100
SpectrumBarHeight=#SBarHeight#
SpectrumBarWidth=#SBarWidth#
SpectrumBarMargin=#SBarMargin#
FontColor=#FontColorGlobal#, 255
FontFace=#FontFaceGlobal#
SkinIcon=#IconMusic#

Caption="NOW PLAYING"
MusicPlayer=AIMP
