;==============================================================================
; Grayhound Large Size Settings
; Needs to be included after Global.inc
;
; @category: Rainmeter
; @package: Grayhound
; @version: 5.6.1
; @date: 2024-06-29
; @author: George Lewe <george@lewe.com>
; @copyright: 2012-2024 by George Lewe
; @link: http://www.lewe.com
; @license: https://creativecommons.org/licenses/by-nc-sa/3.0/
; @documentation: https://lewe.gitbook.io/rainmeter-skin-grayhound
;

[Variables]

;
; Canvas size and positions
;
CanvasWidth=360
CanvasHeight=60
MeterYPos=2
MeterWidth=290
MeterHeight=58
CaptionYPos=10
LegendYPos=32
BarHeight=9
CaptionYRel=100r
LegendYRel=23r
BarYRel=28r
LineYRel=-58r

;
; Font size
;
FontSize=12

;
; CPU Bars
;
CpuBarsLineYPos=220
CpuBarsBarYRel=76r
CoreBarWidth8Cores=28
CoreBarXDist8Cores=9
CoreBarYRel8Cores=120r
CoreBarWidth12Cores=21
CoreBarXDist12Cores=3
CoreBarYRel12Cores=120r
CoreBarWidth16Cores=15
CoreBarXDist16Cores=3
CoreBarYRel16Cores=120r
CoreBarHeight=100
CoreBarMarginBottom=8
CoreSpectrumYPos=60
CoreSpectrumTextXPos=12

;
; Icon left/right positions
;
IconXPosLeft=10
IconXPosRight=310
MeterXPosLeft=70
MeterXPosRight=10

;
; Music skin
;
CoverYPos=36
SBarHeight=146
SBarWidth=11
SBarMargin=1
SpectrumYRel=40r
TrackXPosLeft=86
TrackXPosRight=24
TrackWidth=260
TrackBarHeight=4

;
; Processes skin, Fans skin
;
CaptionMarginBottom=32r
BarMarginBottom=24r
HistoMarginBottom=88r
HistoHeight=58
HistoYRel=-48r
LegendWidth=250

;
; Sidebars
;
SidebarWidth=310

;
; Uptime
;
UptimeFontSize=30
