;==============================================================================
; Grayhound Medium Size Settings
; Needs to be included after Global.inc
; 
; @category Rainmeter
; @package Grayhound
; @version: 4.3.2
; @date: 2020-06-23
; @author George Lewe <george@lewe.com>
; @copyright Copyright (c) 2012-2020 by George Lewe
; @link http://www.lewe.com
; @license https://creativecommons.org/licenses/by-nc-sa/3.0/
;

[Variables]

;
; Canvas size and positions
;
CanvasWidth=320
CanvasHeight=50
MeterYPos=2
MeterWidth=250
MeterHeight=48
CaptionYPos=10
LegendYPos=28
BarHeight=8
CaptionYRel=80r
LegendYRel=18r
BarYRel=23r
LineYRel=-48r

;
; Font size
;
FontSize=10

;
; CPU Bars
;
CpuBarsLineYPos=181
CpuBarsBarYRel=64r
CoreBarWidth8Cores=23
CoreBarXDist8Cores=9
CoreBarYRel8Cores=100r
CoreBarWidth12Cores=18
CoreBarXDist12Cores=3
CoreBarYRel12Cores=100r
CoreBarHeight=80
CoreBarMarginBottom=8
CoreSpectrumYPos=50
CoreSpectrumTextXPos=12

;
; Icon left/right positions
;
IconXPosLeft=10
IconXPosRight=270
MeterXPosLeft=70
MeterXPosRight=10

;
; Music skin
;
CoverYPos=36
SBarHeight=113
SBarWidth=9
SBarMargin=1
SpectrumYRel=40r
TrackXPosLeft=86
TrackXPosRight=24
TrackWidth=226
TrackBarHeight=3

;
; Processes skin, Fans skin
;
CaptionMarginBottom=28r
BarMarginBottom=22r
HistoMarginBottom=76r
HistoHeight=48
HistoYRel=-39r
LegendWidth=210

;
; Sidebars
;
SidebarWidth=270

;
; Uptime
;
UptimeFontSize=25
