;==============================================================================
; Grayhound Large Size Settings
; Needs to be included after Global.inc
; 
; @category Rainmeter
; @package Grayhound
; @version: 4.4.0
; @date: 2022-04-08
; @author George Lewe <george@lewe.com>
; @copyright Copyright (c) 2012-2020 by George Lewe
; @link http://www.lewe.com
; @license https://creativecommons.org/licenses/by-nc-sa/3.0/
;

[Variables]

;
; Canvas size and positions
;
CanvasWidth=248
CanvasHeight=44
MeterYPos=12
MeterWidth=170
MeterHeight=32
CaptionYPos=10
LegendYPos=23
BarHeight=6
CaptionYRel=60r
LegendYRel=18r
BarYRel=17r
LineYRel=-32r

;
; Font size
;
FontSize=8

;
; CPU Bars
;
CpuBarsLineYPos=152
CpuBarsBarYRel=54r
CoreBarWidth8Cores=13
CoreBarXDist8Cores=9
CoreBarYRel8Cores=80r
CoreBarWidth12Cores=12
CoreBarXDist12Cores=2
CoreBarYRel12Cores=80r
CoreBarHeight=60
CoreBarMarginBottom=8
CoreSpectrumYPos=40
CoreSpectrumTextXPos=12

;
; Icon left/right positions
;
IconXPosLeft=10
IconXPosRight=190
MeterXPosLeft=70
MeterXPosRight=10

;
; Music skin
;
CoverYPos=30
SBarHeight=78
SBarWidth=6
SBarMargin=1
SpectrumYRel=22r
TrackXPosLeft=80
TrackXPosRight=20
TrackWidth=150
TrackBarHeight=2

;
; Processes skin, Fans skin
;
CaptionMarginBottom=22r
BarMarginBottom=18r
HistoMarginBottom=56r
HistoHeight=40
HistoYRel=-34r
LegendWidth=140

;
; Sidebars
;
SidebarWidth=200

;
; Uptime
;
UptimeFontSize=18
