[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

FontColor=#FontColorGlobal#,255
FontFace=#FontFaceGlobal#
GPUColor=#ColorUsage#,#BarColorTransparency#
GPUMemColor=#ColorMemory#,#BarColorTransparency#
GPUFanColor=#ColorFan#,#BarColorTransparency#
GPUTempColor=#ColorLow#,#BarColorTransparency#
GPUHistoLineColor=#ColorUsage#,#LineColorTransparency#
GPUHistoFillColor=#ColorGPU#,#HistoColorTransparency#
GPUMemHistoLineColor=#ColorGPUMem#,#LineColorTransparency#
GPUMemHistoFillColor=#ColorGPUMem#,#HistoColorTransparency#
GPUFanHistoLineColor=#ColorGPUFan#,#LineColorTransparency#
GPUFanHistoFillColor=#ColorGPUFan#,#HistoColorTransparency#
GPUTempHistoLineColor=#ColorTempLow#,#LineColorTransparency#
GPUTempHistoFillColor=#ColorTempLow#,#HistoColorTransparency#
SkinIcon=#IconGPU#

MaxGPUFan=8000
MedGPUFan=4000
HiGPUFan=6500
