[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

Caption="TRASH"

BarColorCount=#ColorRecycleBinCount#,#BarColorTransparency#
BarColorSize=#ColorRecycleBinSize#,#BarColorTransparency#
FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
HistoLineColor=#ColorNetwork#,#LineColorTransparency#
HistoFillColor=#ColorNetwork#,#HistoColorTransparency#
SkinIcon="#IconRecycleBinEmpty#"
