[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

Core0Number=0
Core1Number=1
Core2Number=2
Core3Number=3
Core4Number=4
Core5Number=5
Core6Number=6
Core7Number=7
Core8Number=8
Caption="CPU"

FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
BarColor=#ColorUsage#,#BarColorTransparency#
HistoLineColor=#ColorUsage#,#LineColorTransparency#
HistoFillColor=#ColorUsage#,#HistoColorTransparency#
CoreBarWidth=#CoreBarWidth8Cores#
CoreBarXDist=#CoreBarXDist8Cores#
CoreBarYRel=#CoreBarYRel8Cores#
SkinIcon=#IconCPU#
