[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

CaptionRam="RAM"
CaptionSwap="SWAP"

FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
BarColor=#ColorMemory#,#BarColorTransparency#
HistoLineColor=#ColorMemory#,#LineColorTransparency#
HistoFillColor=#ColorMemory#,#HistoColorTransparency#
SkinIcon=#IconMemory#
