;==============================================================================
; Grayhound Variables
;
; @category: Rainmeter
; @package: Grayhound
; @version: 5.6.0
; @date: 2024-06-22
; @author: George Lewe <george@lewe.com>
; @copyright: 2012-2024 by George Lewe
; @link: http://www.lewe.com
; @license: https://creativecommons.org/licenses/by-nc-sa/3.0/
; @documentation: https://lewe.gitbook.io/rainmeter-skin-grayhound
;

[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
BarColor=#ColorUsage#,#BarColorTransparency#
HistoLineColor=#ColorUsage#,#LineColorTransparency#
HistoFillColor=#ColorUsage#,#HistoColorTransparency#
SkinIcon=#IconCPU#
