[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

Core0Number=0
Core1Number=1
Core2Number=2
Core3Number=3
Core4Number=4
Core5Number=5
Core6Number=6
Core7Number=7
Core8Number=8
Core9Number=9
Core10Number=10
Core11Number=11
Core12Number=12
Caption="CPU"

FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
BarColor=#ColorUsage#,#BarColorTransparency#
HistoLineColor=#ColorUsage#,#LineColorTransparency#
HistoFillColor=#ColorUsage#,#HistoColorTransparency#
CoreBarWidth=#CoreBarWidth12Cores#
CoreBarXDist=#CoreBarXDist12Cores#
CoreBarYRel=#CoreBarYRel12Cores#
SkinIcon=#IconCPU#
