;==============================================================================
; Grayhound Meter Settings
;
; @category: Rainmeter
; @package: Grayhound
; @version: 5.6.0
; @date: 2024-06-22
; @author: George Lewe <george@lewe.com>
; @copyright: 2012-2024 by George Lewe
; @link: http://www.lewe.com
; @license: https://creativecommons.org/licenses/by-nc-sa/3.0/
; @documentation: https://lewe.gitbook.io/rainmeter-skin-grayhound
;

[createCanavas]
Meter=String
X=0
Y=0
W=#CanvasWidth#

[showTopLine]
Meter=Image
X=#MeterXPos#
Y=0
W=#MeterWidth#
H=1
SolidColor=#TopLineColor#

[showIcon]
Meter=Image
X=#IconXPos#
Y=0
