[Variables]
;
; Skin settings
;
IconXPos=#IconXPosLeft#
MeterXPos=#MeterXPosLeft#
;IconXPos=#IconXPosRight#
;MeterXPos=#MeterXPosRight#

Caption="Network"

BarColor=#ColorNetwork#,#BarColorTransparency#
FontColor=#FontColorGlobal#
FontFace=#FontFaceGlobal#
HistoLineColor=#ColorNetwork#,#LineColorTransparency#
HistoFillColor=#ColorNetwork#,#HistoColorTransparency#
SkinIcon=#IconNetwork#

; 
; Max and min values
;
MaxDown=#DownMaxNetwork#
MaxUp=#UpMaxNetwork#
